captainVersion: 4
services:
  # Banco de Dados
  $$cap_appname-db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: $$cap_db_password
      POSTGRES_DB: moodle
    volumes:
      - $$cap_appname-db-data:/var/lib/postgresql/data
    caproverExtra:
      notExposeAsWebApp: 'true'

  # Seu Moodle Customizado
  $$cap_appname:
    depends_on:
      - $$cap_appname-db
    image: $$cap_docker_image
    restart: always
    environment:
      # URL Real de Produção
      MOODLE_URL: $$cap_moodle_url

      # Conexão com o Banco (Interna do Docker)
      DB_HOST: srv-captain--$$cap_appname-db
      DB_PORT: 5432
      DB_NAME: moodle
      DB_USER: postgres
      DB_PASS: $$cap_db_password
      DB_TYPE: pgsql

      # Configuração Extra para CapRover (Essencial para HTTPS)
      # O sslproxy=1 é necessário lá pois o CapRover termina o SSL antes de chegar no container
      MOODLE_EXTRA_PHP: "$$cap_extra_php"

    volumes:
      - $$cap_appname-data:/var/www/moodledata
    caproverExtra:
      containerHttpPort: '80'

caproverOneClickApp:
  variables:
    - id: $$cap_docker_image
      label: Sua Imagem Docker
      description: ex: esdrascaleb/moodle-production:latest
      defaultValue: esdrascaleb/moodle-production:latest

    - id: $$cap_moodle_url
      label: URL do Moodle
      description: URL completa com https (ex: https://moodle.seudominio.com)
      defaultValue: https://moodle.exemplo.com

    - id: $$cap_db_password
      label: Senha do Banco (Postgres)
      defaultValue: $$cap_gen_random_hex(16)

    - id: $$cap_extra_php
      label: PHP Extra (Hardening & Proxy)
      description: Configurações cruciais para proxy reverso.
      # No CapRover, como usamos HTTPS, o sslproxy é obrigatório.
      defaultValue: "$CFG->sslproxy = 1; $CFG->reverseproxy = 1;"

  instructions:
    start: >-
      Instalando Moodle Production Ready a partir da sua imagem Docker customizada.
    end: >-
      Deploy finalizado! 
      
      1. Ative o HTTPS nas configurações do App imediatamente.
      2. Se der erro de redirecionamento, verifique se a URL em App Configs começa com https://.
  displayName: Moodle Production (Custom Image)
  isOfficial: false
  description: Deploy de Moodle Stateless via Imagem Docker Hub.