captainVersion: 4

services:
  # Banco interno (somente se o usuário NÃO usar DB externo)
  $$cap_appname-db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: moodle
      POSTGRES_PASSWORD: $$cap_db_password
      POSTGRES_DB: moodle
    volumes:
      - $$cap_appname-db-data:/var/lib/postgresql/data
    caproverExtra:
      notExposeAsWebApp: 'true'
    # "Desativa" o container se o usuário escolher DB externo
    # (CapRover simplesmente ignora porque os envs abaixo não serão válidos)
    <<: $$cap_internal_db_enabled

  $$cap_appname:
    depends_on:
      - $$cap_appname-db
    image: $$cap_docker_image
    restart: always
    environment:
      MOODLE_URL: $$cap_moodle_url

      DB_HOST: $$cap_effective_db_host
      DB_PORT: $$cap_effective_db_port
      DB_TYPE: pgsql
      DB_NAME: moodle
      DB_USER: moodle
      DB_PASS: $$cap_db_password

      MOODLE_ADMIN_USER: $$cap_md_admin_user
      MOODLE_ADMIN_PASS: $$cap_md_admin_pass
      MOODLE_ADMIN_EMAIL: $$cap_md_admin_email

      MOODLE_EXTRA_PHP: '$$cap_extra_php'

      PHP_MEMORY_LIMIT: $$cap_php_memory_limit
      PHP_UPLOAD_MAX_FILESIZE: $$cap_php_upload_max
      PHP_POST_MAX_SIZE: $$cap_php_post_max
      PHP_MAX_EXECUTION_TIME: $$cap_php_max_exec
      PHP_MAX_INPUT_VARS: $$cap_php_input_vars

      MOODLE_VERSION: $$cap_moodle_version
      MOODLE_PLUGINS_JSON: '$$cap_moodle_plugins_json'

    volumes:
      - $$cap_appname-data:/var/www/moodledata
    caproverExtra:
      containerHttpPort: '80'

caproverOneClickApp:
  variables:
    - id: $$cap_docker_image
      label: Docker Image
      defaultValue: esdrascaleb/moodle-docker-php-production:php8.1

    - id: $$cap_moodle_url
      label: Moodle URL
      defaultValue: https://moodle.example.com

    - id: $$cap_use_external_db
      label: Use external database?
      description: yes = use host/port/user/pass | no = create local PostgreSQL
      defaultValue: 'no'
      validRegex: /^(yes|no)$/

    # ===== Banco EXTERNO =====
    - id: $$cap_external_db_host
      label: External DB Host
      validIf:
        condition: $$cap_use_external_db
        equals: 'yes'
      defaultValue: ''
    - id: $$cap_external_db_port
      label: External DB Port
      validIf:
        condition: $$cap_use_external_db
        equals: 'yes'
      defaultValue: '5432'

    # ===== Banco INTERNO =====
    - id: $$cap_internal_db_enabled
      label: INTERNAL FLAG – DO NOT TOUCH
      description: Used internally to enable/disable DB container (CapRover trick)
      defaultValue: |
        {}
      validIf:
        condition: $$cap_use_external_db
        equals: 'no'

    - id: $$cap_effective_db_host
      label: INTERNAL DB HOST SWITCH
      defaultValue: srv-captain--$$cap_appname-db
      validIf:
        condition: $$cap_use_external_db
        equals: 'no'

    - id: $$cap_effective_db_host
      label: EXTERNAL DB HOST SWITCH
      defaultValue: $$cap_external_db_host
      validIf:
        condition: $$cap_use_external_db
        equals: 'yes'

    - id: $$cap_effective_db_port
      label: INTERNAL DB PORT SWITCH
      defaultValue: '5432'
      validIf:
        condition: $$cap_use_external_db
        equals: 'no'

    - id: $$cap_effective_db_port
      label: EXTERNAL DB PORT SWITCH
      defaultValue: $$cap_external_db_port
      validIf:
        condition: $$cap_use_external_db

    - id: $$cap_md_admin_user
      label: Moodle Admin User
      defaultValue: admin

    - id: $$cap_md_admin_pass
      label: Moodle Admin Password
      defaultValue: MoodleAdmin123

    - id: $$cap_md_admin_email
      label: Moodle Admin Email
      defaultValue: admin@example.com

    # ===== PHP extra =====
    - id: $$cap_extra_php
      label: Extra PHP
      defaultValue: '$CFG->sslproxy = 1;'

    - id: $$cap_php_memory_limit
      label: PHP Memory Limit
      description: Max memory per script (default 512M)
      defaultValue: 512M

    - id: $$cap_php_upload_max
      label: PHP Upload Max Filesize
      description: Max file upload size
      defaultValue: 100M

    - id: $$cap_php_post_max
      label: PHP POST Max Size
      description: Must be >= upload size
      defaultValue: 100M

    - id: $$cap_php_max_exec
      label: PHP Max Execution Time
      description: Timeout in seconds
      defaultValue: '600'

    - id: $$cap_php_input_vars
      label: PHP Max Input Vars
      description: Increase for large forms (gradebook etc.)
      defaultValue: '5000'

    # ===== DB =====

    - id: $$cap_db_password
      label: Local DB Password
      defaultValue: $$cap_gen_random_hex(16)

    - id: $$cap_moodle_version
      label: Moodle Version (Branch)
      description: 'Branch or tag from Moodle Git. Example: MOODLE_405_STABLE'
      defaultValue: MOODLE_405_STABLE

    - id: $$cap_moodle_plugins_json
      label: Moodle Plugins JSON
      description: 'JSON array of plugins to install via Git. Example: [{"giturl":"...","branch":...,"installpath":"..."}]'
      defaultValue: '[]'

  instructions:
    start: >
      Moodle Deploy (Custom Image + optional external DB)

    end: >
      Done! Enable HTTPS after deploy.

  displayName: Moodle Production (Custom Image)
  isOfficial: false
  description: Moodle ready for CapRover, with optional external database.
